### ISSUE TITLE
"A second operation started on this context" on transient DbContext

### ISSUE THREAD

**Issue by vladimir-zhmak** [graphql-dotnet/graphql-dotnet#2501]
I have ASP.NET Core 3.1 application with GraphQL 3.2.0
I'll start, that I have transient DbContext registration

```cs
            services.AddDbContext<AppDbContext>(
                options => options.UseNpgsql(this.Configuration.GetValue<string>(OptionKeyConstants.ConnectionString)),
                contextLifetime: ServiceLifetime.Transient,
                optionsLifetime: ServiceLifetime.Transient);
```

then, I define resolver

```cs
    public class MainMutation : ObjectGraphType
    {
        public MainMutation(IServiceLocator locator, IServiceProvider serviceProvider)
        {
			...
            this.FieldAsync<MonolinkElementType>(
                    name: "createMonolinkElement",
                    arguments: new QueryArguments(
                        new QueryArgument<IntGraphType> { Name = "monolinkId" },
                        new QueryArgument<CreateMonolinkElementInput> { Name = "monolinkElement" }),
                    resolve: async context =>
                    {
                        var monolinkId = context.GetArgument<int>("monolinkId");
                        var createMonolinkElementDto = context.GetArgument<CreateMonolinkElementDto>("monolinkElement");

                        return await serviceProvider.GetService<IMonolinkElementService>().CreateAsync(monolinkId, createMonolinkElementDto);
                    })
                .AuthorizeWith(Policies.AuthenticatedUser);
			...
		}
	}
```

and service for business operation:

```cs
    public class MonolinkElementService : IMonolinkElementService
    {
        private readonly AppDbContext dbContext;
        private readonly IMapper mapper;
        private readonly ILogger<MonolinkElementService> logger;

        public MonolinkElementService(AppDbContext dbContext, IMapper mapper, ILogger<MonolinkElementService> logger)
        {
            this.dbContext = dbContext;
            this.mapper = mapper;
            this.logger = logger;
        }
		
        public async Task<MonolinkElementDto> CreateAsync(int monolinkId, CreateMonolinkElementDto createMonolinkElementDto)
        {
            var monolinkElement = this.mapper.Map<MonolinkElement>(createMonolinkElementDto);
            monolinkElement.MonolinkId = monolinkId;

            await this.dbContext.MonolinkElements.AddAsync(monolinkElement);
            await this.dbContext.SaveChangesAsync();

            return this.mapper.Map<MonolinkElementDto>(monolinkElement);
        }
	}
```

On the frontend side I'm sending several requests in a row

```cs
          await Promise.all(
            newMonolinkElements.map(async (i) => {
              try {
                let data  = await createMonolinkElement({
                  variables: {
                    monolinkId: Number(stateRightColum.memoEditedMonolinkObj?.id),
                    monolinkElement: cleanEmpty(i),
                  },
                })

                return data
              } catch (error) {
                console.log('newMonolinkElementsERROR', error)
              }
            })
          ).then(() => {
            setEditRedirect({ ...editRedirect, added: true })
          })
```

In case of 3 requests usually first succeeded and second failed with "System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext."

This very strange, because I have transient dbContext, I'm resolving new service with injected dbContext on each resolver. Even in log output I'm getting different ContextIDs for different queries:

```
[16:28:20 INF] Successfully validated the token.
[16:28:21 INF] MonolinkElementService ctor 9f976a99-1112-4be9-98e2-47e554f550cd:0
[16:28:21 INF] Entity Framework Core 3.1.4 initialized 'AppDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
[16:28:21 INF] HTTP POST /graphql responded 200 in 2055.4365 ms
[16:29:04 INF] HTTP OPTIONS /graphql responded 204 in 0.4586 ms
[16:29:04 INF] Successfully validated the token.
[16:29:04 INF] MonolinkElementService ctor 9cddd3bc-8604-4787-912b-e94489251768:0
[16:29:04 INF] Starting monolink element element with url http://localhost:3002/monolink/edit/2 creation.
[16:29:04 INF] Entity Framework Core 3.1.4 initialized 'AppDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
[16:29:04 INF] Finished monolink element with url http://localhost:3002/monolink/edit/2 creation.
[16:29:04 INF] HTTP POST /graphql responded 200 in 389.9085 ms
[16:29:04 INF] Successfully validated the token.
[16:29:04 INF] MonolinkElementService ctor d30442e3-222d-4b17-a24e-0a689b4cf567:0
[16:29:04 INF] Starting monolink element element with url http://localhost:3002/monolink/edit/3 creation.
[16:29:04 INF] Entity Framework Core 3.1.4 initialized 'AppDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
[16:29:04 ERR] An exception occurred in the database while saving changes for context type 'Heropost.Monolink.Data.AppDbContext'.
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
```

Other very strange finding - if I'm changing to sync resolver - FieldAsync to Field and corresponding service method, then everything works fine.

Any help will be appreciated.

**Comment by Shane32** [comment]
What service lifetime does `IMonolinkElementService` have?  Your errors would make sense if it was scoped.  It would need to be a transient.

**Comment by vladimir-zhmak** [comment]
> What service lifetime does `IMonolinkElementService` have? Your errors would make sense if it was scoped. It would need to be a transient.

Transient. I check this first place.

**Comment by Shane32** [comment]
I assume that the query and graph type classes are registered with your DI framework as singletons? And your schema passes the service provider to the base constructor?

It would seem that either the DbContext isn’t registered as a transient, or IMonolinkElementService isn’t registered as a transient, or something’s up with the service provider.

**Comment by vladimir-zhmak** [comment]
Yes, schema and graph types are singleton

`    public class MainSchema : Schema
    {
        public MainSchema(IServiceProvider services) : base(services)
        {
            this.Query = services.GetService(typeof(MainQuery)).As<IObjectGraphType>();
            this.Mutation = services.GetService(typeof(MainMutation)).As<IObjectGraphType>();
            this.RegisterValueConverter(new FormFileConverter());
        }
    }`

`            services.AddSingleton<ISchema, MainSchema>();
            services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
            services.AddSingleton<MainQuery>();
            services.AddSingleton<MainMutation>();` 

`            // types
            services.AddSingleton<MonolinkElementType>();`

            // inputs
            services.AddSingleton<CreateMonolinkElementInput>();`

And DbContext (see starting post) and IMonolinkElementService are transient
`            // services
            services.AddTransient<IMonolinkElementService, MonolinkElementService>();`

I'm using GraphQL via Middleware from [GraphQL.Server](https://github.com/graphql-dotnet/server) project.
`app.UseGraphQL<ISchema>();`

What else can be an issue?

**Comment by Shane32** [comment]
That is the only possibility that I know of.  GraphQL just runs the resolvers concurrently.  The resolver delegates must handle executing the database requests concurrently, or use a serial execution strategy.

I suggest logging the `.GetHashCode()` of the various objects as they execute - similar to this:
```cs
                    resolve: async context =>
                    {
                        var monolinkId = context.GetArgument<int>("monolinkId");
                        var createMonolinkElementDto = context.GetArgument<CreateMonolinkElementDto>("monolinkElement");

                        var svc = serviceProvider.GetService<IMonolinkElementService>();
                        Debug.WriteLine("create imonolinkelementservice: " + svc.GetHashCode());
                        return await svc.CreateAsync(monolinkId, createMonolinkElementDto);
                    })
```
```cs
        public MonolinkElementService(AppDbContext dbContext, IMapper mapper, ILogger<MonolinkElementService> logger)
        {
            Debug.WriteLine("created monolinkelementservice: " + this.GetHashCode());
            Debug.WriteLine("rec'd db: " + dbContext.GetHashCode());
            this.dbContext = dbContext;
```
```cs
        public async Task<MonolinkElementDto> CreateAsync(int monolinkId, CreateMonolinkElementDto createMonolinkElementDto)
        {
            Debug.WriteLine("run createAsync: " + this.GetHashCode());
```
etc

Then perhaps you can see if somehow the dbcontext or monolink service is the same instance or not.

**Comment by vladimir-zhmak** [comment]
Thank you, I've implemented such logging, but seems, that dbContexts and services are different

`[11:37:21 INF] created monolinkelementservice: 38414640
[11:37:21 INF] dbContext: 1401080
[11:37:21 INF] MonolinkElementService ctor 849a3209-10e0-46cf-9069-03ec4dca315d:0
[11:37:21 INF] create imonolinkelementservice: 38414640
[11:37:21 INF] Starting monolink element element with url http://localhost:3002/monolink/edit/2 creation. Service: 38414640
[11:37:21 INF] Finished monolink element with url http://localhost:3002/monolink/edit/2 creation.
[11:37:21 INF] HTTP POST /graphql responded 200 in 499.3050 ms
[11:37:22 INF] Successfully validated the token.
[11:37:22 INF] created monolinkelementservice: 52637459
[11:37:22 INF] dbContext: 31644831
[11:37:22 INF] MonolinkElementService ctor aefd556a-b200-43bf-8110-ced0bd2a3e05:0
[11:37:22 INF] create imonolinkelementservice: 52637459
[11:37:22 INF] Starting monolink element element with url http://localhost:3002/monolink/edit/3 creation. Service: 52637459
[11:37:22 ERR] An exception occurred in the database while saving changes for context type 'Heropost.Monolink.Data.AppDbContext'.
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)`

**Comment by sungam3r** [comment]
Check if you forgot to call await on some async operation on dbcontext.

**Comment by vladimir-zhmak** [comment]
Really. One missing await and hours of useless debugging.
Thanks a lot.
