### ISSUE TITLE
[v0.17.3] Stackoverflow in MiddlewareResolver, memory leaks

### ISSUE THREAD

**Issue by mRowlinson27** [graphql-dotnet/graphql-dotnet#559]
We've been using GraphQl quite extensively, and have found that after significant use (in thousands) of queries we get a stackoverflow exception. The graphql worker threads will always reveal a stack trace similar to this:

```
00007FD2AD7F6200 00007FD769926D3A GraphQL.dll!GraphQL.Instrumentation.MiddlewareResolver+<Resolve>d__2.MoveNext()+0x1aa
    00007FD2AD7F3AC0 00007FD7668A10BF System.Private.CoreLib.ni.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x1f
    00007FD2AD7F3AD0 00007FD76687E8B5 System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x55
    00007FD2AD7F3AF0 00007FD769926D3A GraphQL.dll!GraphQL.Instrumentation.MiddlewareResolver+<Resolve>d__2.MoveNext()+0x1aa
    00007FD2AD7F13B0 00007FD7668A10BF System.Private.CoreLib.ni.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x1f
    00007FD2AD7F13C0 00007FD76687E8B5 System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x55
    00007FD2AD7F13E0 00007FD769926D3A GraphQL.dll!GraphQL.Instrumentation.MiddlewareResolver+<Resolve>d__2.MoveNext()+0x1aa
    00007FD2AD7EECA0 00007FD7668A10BF System.Private.CoreLib.ni.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x1f
    00007FD2AD7EECB0 00007FD76687E8B5 System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x55
    00007FD2AD7EECD0 00007FD769926D3A GraphQL.dll!GraphQL.Instrumentation.MiddlewareResolver+<Resolve>d__2.MoveNext()+0x1aa
```

which continues for several hundred iterations.

Dumping the object table also reveals that the top memory usage is taken up by purely graphQL objects:

MT | Count | TotalSize | Class Name
-- | -- | -- | --
00007f56acd22248 | 890814 | 37516086 | System.String
00007f56add80288 | 838434 | 60367248 | System.Threading.Tasks.Task`1[[System.Object
00007f56afd11760 | 111570 | 7140480 | System.Func`2[[GraphQL.Types.ResolveFieldContext
00007f56afcba800 | 111570 | 7140480 | GraphQL.Instrumentation.FieldMiddlewareDelegate
00007f56afd115a8 | 111570 | 3570240 | GraphQL.Instrumentation.FieldMiddlewareBuilder+<>c__DisplayClass3_0
00007f56afd11888 | 111570 | 2677680 | GraphQL.Resolvers.FuncFieldResolver`1[[System.Threading.Tasks.Task`1[[System.Object
00007f56afd11698 | 111570 | 2677680 | GraphQL.Instrumentation.MiddlewareResolver
00007f56acccd2a8 | 60198 | 3852672 | System.Action
00007f56acd3c990 | 60144 | 1924608 | System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunnerWithContext
00007f56afd7e200 | 58746 | 5169648 | GraphQL.Instrumentation.MiddlewareResolver+<Resolve>d__2

As you can see, there is over 100,000 graphql objects that are just sitting there taking up space!

From looking at the source code it seems like maybe every call is adding a new resolver to the MiddlewareResolver.next chain until it gets so long it has a stackoverflow? Would that mean there is a problem with our schema? Any thoughts?

**Comment by OneCyrus** [comment]
we have a similiar problem. couldn't find the root cause yet.

this is the memory diff between same apollo requests:

![image](https://user-images.githubusercontent.com/7747800/36247224-7b189908-1233-11e8-8f1f-f8c1fbd21136.png)

**Comment by OneCyrus** [comment]
ok. removing the InstrumentFieldsMiddleware resolves the issue here.

**Comment by mRowlinson27** [comment]
We were not using InstrumentFieldsMiddleware, but changing all our GraphQl Types to being singletons seems to have stopped the count rising. Requires further testing to see if this will fix the stack overflow issue though, and still not 100% on whether this will lead to concurrency issues. Looks promising however

**Comment by mRowlinson27** [comment]
By looking at the graphql codebase, I noticed that if the schema is initialized before use the middlewareresolver class is never actually created. By doing this we seem to have solved the stack overflow issue, not sure if this solution would help anyone who actually has middleware in use though

**Comment by joemcbride** [comment]
In newer versions, you have the option to turn off the field middleware with a flag, just as an FYI.

**Comment by OneCyrus** [comment]
is there a newer version which is stable/usable for production?

while the memory leak is not really visible anymore, the performance gets pretty bad after a few days with the current version. it looks like there are still some issues somewhere.

**Comment by WiredUK** [comment]
For info, to solve a persistent `StackOverflowException` and degrading performance over time, I also had to disable field middleware. To do this, the code is essentially:

    var result = await _documentExecuter.ExecuteAsync(options =>
    {
        //Add this:
        options.SetFieldMiddleware = false;

        options.OperationName = query.OperationName;
        options.Schema = _schema;
        options.Query = query.Query;

        /etc...
    });

**Comment by joaquin-lezama** [comment]
Is this still an issue? Or has been fixed on the current version (2.4.0)?

**Comment by sungam3r** [comment]
I'm sure this issue has been fixed. Now `FieldMiddlewareBuilder` is applied only once to schema.
Also see #1268 with further middleware improvements.

**Comment by ghostknight63** [comment]
Looks like it's still present in the latest preview version.
I have a page which makes 5 graphql requests. 
After 100 page calls here is what I have in memory profiler (500 graphql requests):
![image](https://user-images.githubusercontent.com/22823434/89225152-cf960380-d5ea-11ea-891e-97433c483d8c.png)

And here are results after 200 page calls (1000 graphql requests)
![image](https://user-images.githubusercontent.com/22823434/89225116-c147e780-d5ea-11ea-892e-841123341bd7.png)

Unless I'm missing something that shows that FieldMiddlewareDelegate is being instantiated but never destroyed. Multiple times force GC doesn't help.
All of this instances retain in Gen 2 heap.

These are: 40 page requests, 100 and 200.
![image](https://user-images.githubusercontent.com/22823434/89225346-1d127080-d5eb-11ea-9f84-140468a0c277.png)
![image](https://user-images.githubusercontent.com/22823434/89225398-30254080-d5eb-11ea-9f14-42134f24a61d.png)
