### ISSUE TITLE
Dependency injection with handler/endpoints approach

### ISSUE THREAD

**Issue by mrtes** [graphql-dotnet/graphql-dotnet#730]
I'm currently trying to implement an application with the new handler/endpoints approach, but I'm missing some guidance regarding dependency injection.

In the old system a GraphQL type could have services injected in its constructor by the Schema, for use in more complex resolvers (e.g. get Users from a repository). At the same time basic information was provided by the wrapped model type (e.g. the user model in ObjectGraphType<User>).

In the new system, this separation of the resolvers and a model is not necessarily given. 
In the examples you define and return basic types (e.g. the Droid) and their properties are already set on construction. This corresponds to the the simple resolvers in the old scenario, which would just return properties from their wrapped source object.

Complex resolvers in the new system only have access to specific injected properties, of which only the UserContext is customizeable.
Everything else, be it services or property values, has to be given into a constructor manually because the developer is responsible for creating the types, instead of the schema.

This leaves the following obvious strategies:
- Let the Schema inject services into your Query type (which is still created automatically) and hand it down manually into every subtype.
- Register all services in your UserContext object, to have it accessible in every resolver.
- Make all services static.

I'm not a big fan of either of these ideas. Is there an alternative I'm missing?

**Comment by joemcbride** [comment]
It _should_ work just like the other setup.  You just need to include the `Type`'s that define your resolvers.  The Schema Syntax provides the skeleton of your Schema and the types you include are the resolvers for that schema.

```csharp
_.Types.Include<Query>();
_.Types.Include<MyOtherType>();
```

> Complex resolvers in the new system only have access to specific injected properties, of which only the UserContext is customizeable.

This is also true of the "old system".  The only way to get other services is through injection of the `GraphType` constructor.

Was there something specific you were trying that wasn't working?

**Comment by joemcbride** [comment]
You can introduce a new `DroidType` that represents the `GraphType`, just like `Query` represents a `GraphType`.   `DroidType` is resolved through the container and you can get injected services. Today on `DroidType` you still have to add all the schema defined fields.  For simple properties it would be nice to be able to exclude that and just look at the source object.

[Link for a console app of the following.](https://gist.github.com/joemcbride/2632fd81fabe87cff8a71377058863b5)

```csharp
var schema = Schema.For(@"
  type Droid {
      id: String
      name: String
      friend: Character
  }

  type Character {
      name: String
  }

  type Query {
      hero: Droid
  }
", _ =>
{
    _.Types.Include<DroidType>();
    _.Types.For("Droid").IsTypeOf<Droid>();
    _.Types.Include<Query>();
    _.DependencyResolver = new FuncDependencyResolver(type => container.Get(type));
});

    public class IImportantBusinessObject
    {
        public Guid Id => Guid.NewGuid();
    }

    public class Droid
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }

    public class Character
    {
        public string Name { get; set; }
    }

    public class MyUserContext
    {
    }

    [GraphQLMetadata("Droid")]
    public class DroidType
    {
        public DroidType(IImportantBusinessObject obj)
        {
            Object = obj;
        }

        private IImportantBusinessObject Object {get; set; }

        public string Id(Droid droid) => droid.Id;
        public string Name(Droid droid) => droid.Name + " " + Object.Id.ToString();

        public Character Friend(ResolveFieldContext context, Droid source, MyUserContext context)
        {
            return new Character { Name = "C3-PO" };
        }
    }

    public class Query
    {
        public Query(IImportantBusinessObject obj)
        {
            Object = obj;
        }

        private IImportantBusinessObject Object {get; set; }

        [GraphQLMetadata("hero")]
        public Droid GetHero()
        {
            return new Droid { Id = "1", Name = "R2-D2" };
        }
    }
```

**Comment by mrtes** [comment]
Thank you, that possibility was not obvious to me!
I still don't really get _why_ this works (especially the `ÌsTypeOf` registration). Maybe I have to take a look at the source :)
Anyway, I see that you have added this scenario to the documentation (and tests), which should help clarify the issue for others :+1:

**Comment by joemcbride** [comment]
`IsTypeOf` is optional in this case, but it is good practice to provide one.

https://graphql-dotnet.github.io/docs/getting-started/interfaces#istypeof

I added some overrides to the registration, so you can exclude the `GraphQLMetadata` attribute on the type and do it in the Include.

```csharp
_.Types.Include<DroidType, Droid>("Droid");
```

```graphql
  type Droid {
      id: String
      name: String
      friend: Character
  }
```

The GraphQL schema syntax defines the structure and return types of the GraphQL Type.

```csharp
_.Types.Include<DroidType>("Droid");
```

This `Include` tells the framework - "For the `Droid` schema type, use the fields/methods on `DroidType` as the field resolvers.  For simple types that do not need computed values, you do not have to provide a type with resolvers - the framework will build one with basic resolvers that attempts to read properties on the source object.
